### ISSUE TITLE
 CoffeeScript Compile Task Stops

### ISSUE THREAD

**Issue by CMDann** [redriverpress/CationicStarter#1]
If CoffeeScript contains a syntax error and doesnt compile, it exits the task

**Comment by gmcgibbon** [comment]
Beat me to it. Yes, this is a known issue.

When running `ionic serve` and saving a syntactically incorrect CoffeeScript file, the coffee task runs, displays the syntax error stack, and silently terminates the task.

**Comment by gmcgibbon** [comment]
Finally found some time to work on this. I've found a solution to the coffee task breaking issue and will have it implemented by tomorrow.

**Comment by CMDann** [comment]
:+1:
